[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
GNSSSignals = "52c80523-2a4e-5c38-8979-05588f836870"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[sources]
GNSSSignals = {path = "/home/schoenbrod/Code/GNSSSignals.jl"}
