name: Benchmark this PR
on:
  pull_request_target:
    branches: [ master ]  # change to your default branch
permissions:
  pull-requests: write    # action needs to post a comment

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: MilesCranmer/AirspeedVelocity.jl@action-v1
        with:
          julia-version: '1'
          extra-pkgs: Unitful
          bench-on: ${{github.event.pull_request.head.sha}}